# src/priceoye/data.py

# Comprehensive Data for PriceOye Customer Service Agent

faq_db = {
    "What is the warranty period for mobile phones?": "All mobile phones come with a 1-year brand warranty, PTA-approved, unless otherwise specified on the product page.",
    "How do I track my order?": "Log into your PriceOye account, go to 'Track my Order,' or use the tracking ID sent via SMS/email. You can also track via AfterShip using the provided tracking number.",
    "Do you offer open box deliveries?": "Yes, open-box delivery is available in Islamabad, Rawalpindi, Lahore, and Karachi for PKR 300, allowing you to check the product before payment.",
    "What are the charges for home delivery?": "Standard home delivery is free across Pakistan. For open-box delivery, a PKR 300 fee applies in select cities.",
    "What is the process for installments?": "Installments are available through partnered banks. At checkout, select the installment option, provide required details (e.g., CNIC, phone number), and follow the bank’s approval process.",
    "What is PriceOye’s return policy?": "PriceOye offers a 3-day return policy for faulty or incorrect products. Contact us via WhatsApp or log a complaint on your PriceOye account with an unboxing video.",
    "Can I return a product if I change my mind?": "No, returns are not accepted for a change of mind. Returns are only valid for faulty products or items different from what was ordered.",
    "What is required for a valid return?": "Provide a complete unboxing video showing the company’s flyer, ensure no items are missing or damaged, and file a complaint within 3 days of delivery.",
    "How do I file a complaint for a return?": "Log into your PriceOye account, go to 'Complaints,' provide details of the issue, and attach an unboxing video and a video of the problem.",
    "What happens if the returned product has no issue?": "If the product is found to have no valid issue after inspection, it will be sent back to the customer.",
    "Can I exchange a product?": "Exchanges are allowed within 3 days for faulty or incorrect products, subject to the same return conditions.",
    "What is the warranty for accessories?": "Most accessories come with a 6-month to 1-year warranty, depending on the product. Check the product page for details.",
    "How long does delivery take?": "Delivery takes 2-5 business days across Pakistan. In Islamabad and Rawalpindi, 24-hour delivery is available for in-stock items.",
    "Is delivery free?": "Yes, PriceOye offers free delivery across Pakistan on all orders.",
    "What is open parcel delivery?": "Open parcel delivery allows you to check the product before paying the rider, available in Islamabad, Rawalpindi, Lahore, and Karachi for PKR 300.",
    "What should I do upon receiving my parcel?": "Check the package for damage, make an unboxing video starting from the company’s flyer, and contact customer care within 24 hours if there’s an issue.",
    "Can I cancel my order?": "Orders can be canceled before shipping by calling 051-111-693-693. Once shipped, cancellation is not possible.",
    "Can I change the delivery address?": "No, the delivery address cannot be changed after the order is placed. Cancel and reorder with the correct address.",
    "What if I receive a damaged product?": "Contact customer care within 24 hours with an unboxing video. File a complaint on your account for a replacement or refund.",
    "Are all products PTA-approved?": "Yes, all mobile phones sold on PriceOye are PTA-approved and come with a 1-year brand warranty.",
    "Do you sell second-hand products?": "No, PriceOye only sells original, sealed-pack products with brand warranties.",
    "What payment methods are available?": "We accept cash on delivery, credit/debit cards, bank transfers, and installment plans via partnered banks.",
    "Is cash on delivery available?": "Yes, cash on delivery is available across Pakistan with no additional charges.",
    "Why is my payment held for 24 hours?": "Payment gateways hold deliveries for 24 hours to ensure secure transactions. Products are dispatched after confirmation.",
    "What is PriceOye Assured?": "PriceOye Assured guarantees authentic products, PTA approval, and replacement for damaged or incorrect items.",
    "Can I pick up my order myself?": "Yes, self-pickup is available from PriceOye warehouses in Islamabad, Karachi, and Lahore. Check the Self Pickup Policy for details.",
    "What is the self-pickup process?": "Place your order, select self-pickup, and collect from an authorized PriceOye warehouse or Experience Centre in Islamabad, Karachi, or Lahore.",
    "What if I miss my delivery?": "If you miss delivery, the courier will attempt redelivery. After 6 months of no response, unclaimed products may be discarded.",
    "How do I contact customer support?": "Call 051-111-693-693 or email us. You can also log complaints via your PriceOye account.",
    "Do you offer refunds?": "Refunds are processed for valid returns (faulty or incorrect products) within 3 days of delivery, after inspection.",
    "How long does a refund take?": "Refunds are processed within 7-10 business days after the returned product is inspected and approved.",
    "What if I receive an empty box?": "Contact customer care within 24 hours with an unboxing video as evidence. File a complaint for resolution.",
    "Are prices inclusive of taxes?": "No, prices listed are generally exclusive of taxes and fees, which may vary by location and retailer.",
    "Can I buy directly from PriceOye?": "Yes, you can purchase directly from priceoye.pk. We also provide links to trusted retailers for some products.",
    "How do I check my warranty status?": "For brands like Realme, check warranty status on the brand’s official website (e.g., Oppo Pakistan’s warranty page).",
    "What is the delivery schedule?": "Deliveries are made Monday to Saturday, 9:00 AM to 8:00 PM.",
    "Do you deliver to all areas in Pakistan?": "Yes, we deliver across Pakistan, though delivery times may vary based on location.",
    "What if the courier doesn’t contact me?": "Track your order via your account or AfterShip. Contact customer care if there’s no update.",
    "Can I change the product color after ordering?": "Color changes are possible before shipping if the payment hasn’t been processed. Contact customer care.",
    "What is the packing video proof?": "PriceOye sends a video link showing your product being packed before dispatch to ensure transparency.",
    "Why do I need to provide my CNIC?": "A CNIC picture is required for delivery verification to ensure the package reaches the authorized recipient.",
    "What if my product is not PTA-approved?": "All PriceOye products are PTA-approved. Contact customer care if you face any issues.",
    "Do you offer discounts?": "Yes, PriceOye offers competitive prices and periodic discounts. Check the website for current deals.",
    "How do I know if a product is in stock?": "In-stock products are marked on the product page. Delivery times may vary if shipped from another city.",
    "What happens if my order is delayed?": "Delays may occur due to protests or courier issues. Contact customer care for updates.",
    "Can I order accessories separately?": "Yes, accessories like earbuds, chargers, and smartwatches are available for purchase.",
    "What if my accessory is faulty?": "Faulty accessories can be returned within 3 days with an unboxing video, subject to warranty terms.",
    "Do you sell laptops or VR headsets?": "Currently, PriceOye focuses on mobile phones and accessories but may expand to other electronics in the future.",
    "How do I stay updated on new products?": "Subscribe to the PriceOye newsletter or follow us on social media for updates on new releases and deals.",
    "What is the process for fraud claims?": "Provide a comprehensive unboxing video and file a complaint within 3 days. Fraudulent claims without evidence will be rejected.",
    "Why was my order canceled?": "Orders may be canceled due to product unavailability, pricing errors, or suspected fraud. You’ll be notified with a reason.",
    "How do I provide feedback?": "Log into your account, go to 'Complaints,' or contact customer care to share feedback.",
    "What if I receive a different product?": "File a complaint within 3 days with an unboxing video. We’ll arrange a replacement or refund after inspection.",
    "Do you offer corporate discounts?": "Contact customer care for inquiries about bulk or corporate orders.",
    "How secure is my personal information?": "PriceOye collects personal data (name, email, address) to process orders and improve services, as outlined in our Privacy Policy."
}

order_db = {
    "order1001": {"status": "shipped", "tracking": "PK123456789", "delivery_date": "2025-05-01"},
    "order1002": {"status": "processing", "tracking": None}
}

product_db = {
    "Samsung Galaxy A54": {"price": 79999, "ram": "8GB", "storage": "128GB", "camera": "50MP"},
    "Infinix Note 30": {"price": 49999, "ram": "6GB", "storage": "64GB", "camera": "48MP"},
    "Realme C53": {"price": 34999, "ram": "4GB", "storage": "64GB", "camera": "50MP"},
    "Tecno Spark 20": {"price": 29999, "ram": "4GB", "storage": "128GB", "camera": "50MP"},
    "Apple iPhone 15": {"price": 249999, "ram": "6GB", "storage": "128GB", "camera": "48MP"},
    "Xiaomi Redmi Note 13": {"price": 64999, "ram": "8GB", "storage": "256GB", "camera": "108MP"},
    "Oppo Reno 11": {"price": 129999, "ram": "8GB", "storage": "256GB", "camera": "64MP"},
    "Vivo Y17s": {"price": 39999, "ram": "4GB", "storage": "128GB", "camera": "50MP"},
    "Samsung Galaxy S23": {"price": 199999, "ram": "8GB", "storage": "256GB", "camera": "50MP"},
    "Infinix Hot 40": {"price": 44999, "ram": "8GB", "storage": "128GB", "camera": "50MP"},
    "Realme Narzo 50": {"price": 52999, "ram": "6GB", "storage": "128GB", "camera": "48MP"},
    "Tecno Camon 20": {"price": 56999, "ram": "8GB", "storage": "256GB", "camera": "64MP"},
    "Apple iPhone 14": {"price": 229999, "ram": "6GB", "storage": "128GB", "camera": "12MP"},
    "Xiaomi 14": {"price": 179999, "ram": "12GB", "storage": "512GB", "camera": "50MP"},
    "Oppo A58": {"price": 54999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Vivo V29": {"price": 139999, "ram": "12GB", "storage": "256GB", "camera": "50MP"},
    "Samsung Galaxy A34": {"price": 69999, "ram": "6GB", "storage": "128GB", "camera": "48MP"},
    "Infinix Zero 30": {"price": 79999, "ram": "12GB", "storage": "256GB", "camera": "108MP"},
    "Realme 11 Pro": {"price": 89999, "ram": "8GB", "storage": "256GB", "camera": "100MP"},
    "Tecno Pova 5": {"price": 47999, "ram": "8GB", "storage": "128GB", "camera": "50MP"},
    "Apple iPhone 16": {"price": 279999, "ram": "8GB", "storage": "128GB", "camera": "48MP"},
    "Xiaomi Poco X6": {"price": 74999, "ram": "8GB", "storage": "256GB", "camera": "64MP"},
    "Oppo Find X7": {"price": 189999, "ram": "12GB", "storage": "512GB", "camera": "50MP"},
    "Vivo Y36": {"price": 45999, "ram": "8GB", "storage": "128GB", "camera": "50MP"},
    "Samsung Galaxy Z Fold 6": {"price": 499999, "ram": "12GB", "storage": "512GB", "camera": "50MP"},
    "Infinix GT 10 Pro": {"price": 69999, "ram": "8GB", "storage": "256GB", "camera": "108MP"},
    "Realme C67": {"price": 42999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Tecno Phantom V Fold": {"price": 249999, "ram": "12GB", "storage": "512GB", "camera": "50MP"},
    "Apple iPhone 13": {"price": 199999, "ram": "4GB", "storage": "128GB", "camera": "12MP"},
    "Xiaomi Redmi 12": {"price": 39999, "ram": "4GB", "storage": "128GB", "camera": "50MP"},
    "Oppo A78": {"price": 59999, "ram": "8GB", "storage": "256GB", "camera": "50MP"},
    "Vivo Y27": {"price": 48999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Samsung Galaxy A14": {"price": 45999, "ram": "4GB", "storage": "64GB", "camera": "50MP"},
    "Infinix Note 40 Pro": {"price": 64999, "ram": "8GB", "storage": "256GB", "camera": "108MP"},
    "Realme 12 Pro": {"price": 79999, "ram": "8GB", "storage": "256GB", "camera": "50MP"},
    "Tecno Spark 10 Pro": {"price": 39999, "ram": "8GB", "storage": "128GB", "camera": "50MP"},
    "Apple iPhone 15 Pro": {"price": 299999, "ram": "8GB", "storage": "256GB", "camera": "48MP"},
    "Xiaomi 13T": {"price": 159999, "ram": "12GB", "storage": "256GB", "camera": "50MP"},
    "Oppo Reno 10": {"price": 119999, "ram": "8GB", "storage": "256GB", "camera": "64MP"},
    "Vivo V30": {"price": 149999, "ram": "12GB", "storage": "512GB", "camera": "50MP"},
    "Samsung Galaxy S24": {"price": 249999, "ram": "8GB", "storage": "256GB", "camera": "50MP"},
    "Infinix Hot 30": {"price": 37999, "ram": "4GB", "storage": "128GB", "camera": "50MP"},
    "Realme C35": {"price": 35999, "ram": "4GB", "storage": "64GB", "camera": "50MP"},
    "Tecno Camon 19": {"price": 49999, "ram": "6GB", "storage": "128GB", "camera": "64MP"},
    "Samsung Galaxy A24": {"price": 64999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Infinix Smart 8": {"price": 24999, "ram": "4GB", "storage": "64GB", "camera": "13MP"},
    "Realme Narzo 60": {"price": 59999, "ram": "8GB", "storage": "128GB", "camera": "64MP"},
    "Tecno Pova Neo": {"price": 42999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Samsung Galaxy A04s": {"price": 34999, "ram": "4GB", "storage": "64GB", "camera": "50MP"},
    "Infinix Zero Ultra": {"price": 99999, "ram": "8GB", "storage": "256GB", "camera": "200MP"},
    "Realme GT Neo 5": {"price": 109999, "ram": "12GB", "storage": "256GB", "camera": "50MP"},
    "Tecno Spark Go 2024": {"price": 23999, "ram": "4GB", "storage": "64GB", "camera": "13MP"},
    "Samsung Galaxy Buds 2": {"price": 19999, "type": "earbuds", "battery": "20 hours", "feature": "ANC"},
    "Xiaomi Power Bank 10000mAh": {"price": 4999, "type": "power bank", "capacity": "10000mAh", "feature": "Fast Charging"},
    "Realme Buds Air 5": {"price": 12999, "type": "earbuds", "battery": "25 hours", "feature": "Noise Cancellation"},
    "Infinix Charger 33W": {"price": 2999, "type": "charger", "power": "33W", "feature": "Fast Charging"},
    "Oppo Smartwatch 2": {"price": 24999, "type": "smartwatch", "battery": "7 days", "feature": "AMOLED Display"},
    "Vivo TWS Earbuds": {"price": 14999, "type": "earbuds", "battery": "24 hours", "feature": "IP54"},
    "Samsung 25W Charger": {"price": 3999, "type": "charger", "power": "25W", "feature": "Super Fast Charging"},
    "Xiaomi Mi Band 8": {"price": 9999, "type": "fitness tracker", "battery": "14 days", "feature": "AMOLED"},
    "Realme Power Bank 20000mAh": {"price": 6999, "type": "power bank", "capacity": "20000mAh", "feature": "Quick Charge"},
    "Infinix Smartwatch XW1": {"price": 15999, "type": "smartwatch", "battery": "10 days", "feature": "Heart Rate Monitor"},
    "Tecno Earbuds T1": {"price": 7999, "type": "earbuds", "battery": "20 hours", "feature": "Touch Control"},
    "Samsung Galaxy Watch 6": {"price": 59999, "type": "smartwatch", "battery": "2 days", "feature": "ECG Monitoring"},
    "Xiaomi Redmi Buds 4": {"price": 10999, "type": "earbuds", "battery": "22 hours", "feature": "ANC"},
    "Oppo 65W Charger": {"price": 5999, "type": "charger", "power": "65W", "feature": "SuperVOOC"},
    "Vivo Power Bank 15000mAh": {"price": 5999, "type": "power bank", "capacity": "15000mAh", "feature": "Dual Port"},
    "Samsung Galaxy A05": {"price": 31999, "ram": "4GB", "storage": "64GB", "camera": "50MP"},
    "Infinix Hot 50": {"price": 45999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Realme Note 50": {"price": 38999, "ram": "4GB", "storage": "128GB", "camera": "50MP"},
    "Tecno Camon 21": {"price": 61999, "ram": "8GB", "storage": "256GB", "camera": "64MP"},
    "Samsung Galaxy A15": {"price": 49999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Infinix Note 50": {"price": 69999, "ram": "8GB", "storage": "256GB", "camera": "108MP"},
    "Realme C65": {"price": 41999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Tecno Spark 20 Pro": {"price": 45999, "ram": "8GB", "storage": "256GB", "camera": "108MP"},
    "Samsung Galaxy S23 FE": {"price": 179999, "ram": "8GB", "storage": "128GB", "camera": "50MP"},
    "Infinix Zero 40": {"price": 89999, "ram": "12GB", "storage": "512GB", "camera": "108MP"},
    "Realme 13 Pro": {"price": 99999, "ram": "12GB", "storage": "256GB", "camera": "50MP"},
    "Tecno Phantom X2": {"price": 149999, "ram": "8GB", "storage": "256GB", "camera": "64MP"},
    "Samsung Galaxy A25": {"price": 79999, "ram": "6GB", "storage": "128GB", "camera": "50MP"},
    "Infinix GT 20 Pro": {"price": 79999, "ram": "12GB", "storage": "256GB", "camera": "108MP"},
    "Realme C55": {"price": 36999, "ram": "6GB", "storage": "128GB", "camera": "64MP"},
    "Tecno Pova 6 Pro": {"price": 59999, "ram": "8GB", "storage": "256GB", "camera": "108MP"},
    "Samsung Galaxy Z Flip 6": {"price": 299999, "ram": "12GB", "storage": "256GB", "camera": "50MP"},
    "Infinix Smart 9": {"price": 26999, "ram": "4GB", "storage": "64GB", "camera": "13MP"},
    "Realme Narzo 70": {"price": 64999, "ram": "8GB", "storage": "256GB", "camera": "50MP"},
    "Tecno Spark 11": {"price": 34999, "ram": "4GB", "storage": "128GB", "camera": "50MP"},
    "Samsung 45W Charger": {"price": 4999, "type": "charger", "power": "45W", "feature": "Super Fast Charging"},
    "Xiaomi Smartwatch S1": {"price": 29999, "type": "smartwatch", "battery": "12 days", "feature": "AMOLED"},
    "Realme Buds T100": {"price": 8999, "type": "earbuds", "battery": "20 hours", "feature": "ENC"},
    "Infinix Power Bank 10000mAh": {"price": 4499, "type": "power bank", "capacity": "10000mAh", "feature": "Fast Charging"},
    "Tecno Charger 18W": {"price": 1999, "type": "charger", "power": "18W", "feature": "Quick Charge"}
}

cart_status = {
    "cart001": "abandoned",
    "cart002": "active"
}